### create
POST localhost:8081/article
Content-Type: application/json

{
  "title": "lkdfsjg",
  "content": "sdgdsfg",
  "description": "sdgsdsdg",
  "imageId": 3,
  "regionId": 1,
  "categoryIds": [1, 2],
  "sectionIds": [1, 2]
}

### get by id
GET localhost:8081/article/3

### update by id
PUT localhost:8081/article/2
Content-Type: application/json

{
  "title": "Java",
  "content": "Programming language",
  "description": "Learning with ai",
  "imageId": 5,
  "regionId": 1,
  "sectionIds": [1],
  "categoryIds": [2]
}

### delete by id
DELETE localhost:8081/article/5

### change status
PUT localhost:8081/article/change-status
Content-Type: application/json

{
  "articleId": 2,
  "status": "PUBLISHED"
}

### pagination by section id
GET localhost:8081/article/pagination-by-section-id/2?page=1&size=1

### pagination except for ids
GET localhost:8081/article/pagination-except-ids/?page1
Content-Type: application/json

{
  "ids": [2]
}
