
### createa attach
POST http://localhost:8081/attach/upload
Content-Type: multipart/form-data; boundary=WebAppBoundary

--WebAppBoundary
Content-Disposition: form-data; name="file"; filename="sdgsfg.jpg"

< C:\Users\user\Desktop\images\football.jpg

### OpenSimple
GET http://localhost:8081/attach/open/football.jpg

### open
GET http://localhost:8081/attach/aade7385-b0c8-4c54-97d4-a867922be8b0.png

### download
GET http://localhost:8081/attach/download/5da894f9-84af-4268-9c5a-a5663b0f0c30.jpg

