
### createa attach
POST http://localhost:8081/attach/upload
Content-Type: multipart/form-data; boundary=WebAppBoundary

--WebAppBoundary
Content-Disposition: form-data; name="file"; filename="sdgsfg.mkv"

< C:\Users\user\Desktop\images\friends.mkv

### OpenSimple
GET http://localhost:8081/attach/open/football.jpg

### open
GET http://localhost:8081/attach/3b8af4a1-7d95-4d77-a8fc-f330908f304e.mkv

### download
GET http://localhost:8081/attach/download/aa80afe9-445b-4112-8013-dace0c57b272.mkv

### delete by id
DELETE http://localhost:8081/attach/delete-by-id/3b8af4a1-7d95-4d77-a8fc-f330908f304e.mkv

